teleop_G: # "Right" arm
  port: "/dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT88YYGL-if00-port0"
  ids: [1,2,3,4,5,6,7]
  joint_offsets: [2, 3, 3, 1, 3, 0, 0] #[3, 2, 0, 1, 1, 3, 0] #in multiples of np.pi / 2
  gripper_config: [8, 192, 150]

teleop_C: # "Left" arm
  port: "/dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FTA2U2O3-if00-port0"
  ids: [1,2,3,4,5,6,7]
  joint_offsets: [1, 2, 3, 1, 3, 2, 2]  # in multiples of np.pi/2
  gripper_config: [8, 190, 148]

gripper:
  port: "/dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FTA2U12T-if00-port0"
  arm_ip: "192.168.1.195"
  reset_joints: [84.6, -85.2, -13.2, 63.6, 22.5, 21.1, 64, 0] #degrees. Assumed initial position of the arms
  #array([ 1.47654855, -1.48702052, -0.23038346,  1.1100294 ,  0.39269908, 0.36826447,  1.11701072])
  ids: [1,2,4]

cutter:
  port: "/dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT89I74E-if00-port0"
  arm_ip: "192.168.1.201"
  reset_joints: [0, 0, 0, 90, 0, 0, 0, 0] #degrees. Assumed initial position of the arms
  id: 0