camera:
  fhrsense_serial: '130322272760'
  gripper_serial: '128422272240'
  teleop_serial: '819112072363'
gripper: # left arm 
  arm_ip: 192.168.1.230
  ids:
  - 1
  - 2
  - 4
  port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT89I74E-if00-port0
  reset_joints:
  - -109.3
  - -81.7
  - -6.4
  - 68
  - 22.9
  - 16
  - 174
  - 0
fhrsense: # right arm
  arm_ip: 192.168.1.241
  ids:
  - 1
  - 2
  - 3
  - 4
  port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FTA2U12T-if00-port0
  tool_ranges:
  - -2.0
  - -2.0 
  - -2.0
  - -2.0
  baudrate: 2000000
  reset_joints:
  - 118.7
  - -88
  - -6.2
  - 58.8
  - -31.7
  - 30
  - 99.4
  - 0
teleop_left:
  gripper_config:
  - 8
  - 190
  - 148
  ids:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  joint_offsets:
  - 2
  - 2
  - 4
  - 1
  - 1
  - 3
  - -1
  joint_signs:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FTA2U2O3-if00-port0
teleop_right:
  gripper_config:
  - 8
  - 192
  - 150
  ids:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  joint_offsets:
  - 2
  - 3
  - 3
  - 1
  - 3
  - 0
  - 0
  joint_signs:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT88YYGL-if00-port0
